name: Build and Publish Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Haal de code op
      uses: actions/checkout@v3

    - name: Log in op GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build en push image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name | lower }}:latest .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name | lower }}:latest

